#!/bin/bash
source /vagrant/.stackrc

TEN=$(keystone tenant-list | awk '/\ service\ / {print $2}');
neutron net-create --tenant-id $TEN --router:external=True provider-net
neutron subnet-create --tenant-id $TEN --name public-subnet --allocation-pool start=192.168.80.20,end=192.168.80.99 --gateway 192.168.80.10 --enable_dhcp=False provider-net 192.168.80.0/24
neutron router-create tenant-router
neutron router-gateway-set tenant-router provider-net
neutron net-create frontend-network
neutron subnet-create --name frontend-subnet1 --dns-nameserver 8.8.8.8 frontend-network 172.31.0.0/24
neutron router-interface-add tenant-router frontend-subnet1
#neutron net-create backend-network
#neutron subnet-create --name backend-subnet1 backend-network 10.0.0.0/8

